admin:
  username: admin
  password: admin
  email: admin@gmail.com
server:
  port: 8080
spring:
  application:
    name: D learning_Service
  datasource:
    url: jdbc:postgresql://localhost:5432/d_learning
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: vovannghiahiep1562003@gmail.com
    password: zuvzquhzgbnmvqqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secretKey: 90c85b588e8d468d45cf5a70a5517dc6507a0655d7ea0664f6eb70dd4d76394e
  valid-duration: 86400
  refresh-duration: 86400
cloudinary:
  cloud_name: dqnwxejgy
  api_key: 486184719822545
  api_secret: XOtBNDM_B6EzTK9TUQ9ET1CBDHA